name: docker-push

on:
  # workflow_dispatch:
  # push:
  #   branches:
  #     - 'main'

env:
  RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:API"  
          push: true
          tags: remixkg6/datingapp:latest

  deploy:
    needs: docker
    name: Deploy App
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Deploy using the Render API
        run: |
          curl -X POST "${{ secrets.DEPLOY_HOOK_URL }}"  # Use double curly braces here
